### PR TITLE
Refactoring + introduce allow dns resolution binding

### PR DESCRIPTION
**Pull request by vburckhardt**
### Description

Related to https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/652

Found some inconsistencies / anti-pattern as I was adding the allow_dns_resolution_binding input in the module. This PR exposes allow_dns_resolution_binding but also fixes those inconsistencies as opposed to build on top of a fragile foundation.

- Fix internal inconsistencies between the way the VPE details were passed for multi-tenant and single-tenant VPEs (cloud_services and cloud_service_by_crn variable now follow the same type and naming conventions)
- Renamed some fields to more accurate and precise terms
- Removed vpe_names variable. This is now replace with the vpe_name field in the cloud_services and cloud_service_by_crn 
- Also fixed a bug where the reserved ips were not named

Whilst the interface of module changes, there is no deletion of resources when moving up to this new version, assuming to coherent parameters are passed as input.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by vburckhardt** [comment]
TODO: adjust readme usage

**Review by toddgiguere — APPROVED** [review]

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
