### PR TITLE
Fix VPE gateway details in output through datasource

### PR DESCRIPTION
**Pull request by vbontempi**
### Description

This PR fixes the issue with the VPE gateway details returned in output: the fix is with using ibm_is_virtual_endpoint_gateway datasource to load the gateway details once all the resources are completely deployed instead of returning the ibm_is_virtual_endpoint_gateway resource details. 

### Release required?

- [ ] No release
- [X] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Fix issue with the VPE gateway details returned in output

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Review by ocofaigh — COMMENTED** [review]
Can we maybe update the test to ensure that the output is not empty? Similar to what we did in https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/267 ?

**Comment by vbontempi** [comment]
@ocofaigh I added the code to perform a further output validation. The existing code checks for a set of keys to exist, while in this specific case the key exists but its content was wrong (a set of slices, empty instead of containing values) 
I added a code to perform this kind of check on the output structure. 
Maybe it could be a good start to have something more generic that can be used in other tests
Adding @toddgiguere and @daniel-butler-irl as reviewers

**Review by ocofaigh — COMMENTED** [review]
@vbontempi Can you explain why adding a data source resolves the problem here? I thought the issue was that the `vpe_ips` output was not containing any IPs because they were not yet available on the backend. Is it not still possible that the IPs will not be ready when the data lookup occurs?

**Comment by vbontempi** [comment]
> @vbontempi Can you explain why adding a data source resolves the problem here? I thought the issue was that the `vpe_ips` output was not containing any IPs because they were not yet available on the backend. Is it not still possible that the IPs will not be ready when the data lookup occurs?

According to what discussed with provider developer, the current behavior is the expected one (even if the user experience is not optimal): the information are not available to the resource ibm_is_virtual_endpoint_gateway when the resource is created, so the output is almost empty
The datasource is configured as depending on the last resource been created at deployment time (the endpoint_gateway_ip) so when it runs all the information are fully available. 

The same cannot be done in the resource ibm_is_virtual_endpoint_gateway as it would create a dependency cycle, as ibm_is_virtual_endpoint_gateway_ip is indirectly depending on ibm_is_virtual_endpoint_gateway for the vpes map

This is a workaround, waiting for the issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4738 to be addressed

**Pull request merged**
