### PR TITLE
fix: available service endpoints added/fixed

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Contains fixes and additions to the available multitenant services that can be configured with a Virtual Private Endpoint gateway.

Made sure that all multitenant services are tested.

fixes https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/issues/396
fixes https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/issues/390

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Added new endpoints that are now available to be requested in the `cloud_services` input variable:
- context-based-restrictions
- ntp

Fixed issue with following service, endpoint will now properly deploy in region:
- container-registry

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by vburckhardt** [comment]
Hi Todd, I see a few more hpcs endpoints to add. The current logic only allows creating the api one.

image

Also tagging missing
image

Cos Config endpoint is missing as well
image

**Comment by vburckhardt** [comment]
support center
image

**Comment by toddgiguere** [comment]
@vburckhardt the challenge I am seeing is that the terraform block only supports adding via CRN or "name", and right now the only one that has "name" was "ntp".

If we can query `ibmcloud is endpoint-gateway-targets` and see the service, that is typically where I've been getting either the CRN or the official "name". I can check if any of these show up.

I haven't found a way to add a VPE endpoint by simply knowning its https endpoint, unless I'm missing something?

**Comment by toddgiguere** [comment]
@vburckhardt I think I found all of these, and their configuration CRNs, and also some extra that I've found:
- for hs-crypto, I can set the name of the service to have a suffix? such as "hs-crypto-cert-mgr"?
- we already had "tagging", it is called "global-search-tagging"
- COS config is found, will add
- support center is found, will add

I've also found the following which I can add:
- containers-kubernetes
- sos (pimconsole.sos.ibm.com is endpoint? I'm not sure what this is?)
- messaging
- vmware

Let me know if we do not want to add those.

**Comment by toddgiguere** [comment]
@vburckhardt you might notice that the PR test does not include all services, many are commented out. That is because I wanted the Upgrade test to run (the new services aren't available in main version). Once we get this PR released I will follow up with a test PR which will uncomment those services out, and at that point we will be testing them all.

I've already confirmed they are all working by running the `every-mt-vpe` example locally.

**Review by vburckhardt — APPROVED** [review]
Awesome. Thanks for this.

**Pull request merged**
